services:

  service-1:
    working_dir: ./
    command: |
      echo "Hello World"
      sleep 10
      echo "Bye"

  service-2:
    working_dir: ./
    command: |
      echo Wazzup; sleep 5
      cd /
      ls

  service-http-server:
    working_dir: ./
    command: |
      echo "Start server on http://127.0.0.1:8000/ in project directory"
      python -m SimpleHTTPServer